95% payroll-frame
CoteriePH/rdi-payroll-system pull request #238
Opened 2021-12-01 14:12 UTC by CloudyMushroom

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Screenshots (if appropriate)

Add screenshots that could help the reviewer.

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules

2021-12-01 14:15 UTC, CloudyMushroom commented
![Uploading image.png…]()
Itong part baka merong library yung react para sa scrollable year/date picker? so depende na lang sa inyo. Once na integrate na yung scrollable year/date.(kung meron man) then if may papadagdag na design let me know na lang.

2021-12-05 02:11 UTC, franzegos commented
nice, @glendell03  okay lang palipat ulit to pri? yung nasa auditor.attendance ililipat sana ditoo 
![image](https://user-images.githubusercontent.com/71435340/144730789-8abb9e31-7926-4626-92d0-13068e48761c.png)

2021-12-05 02:32 UTC, glendell03 commented
> 
> ![image](https://user-images.githubusercontent.com/74799765/144250129-0cd33482-4df6-45f3-8464-5b077c0ae689.png)
> ![image](https://user-images.githubusercontent.com/74799765/144250129-0cd33482-4df6-45f3-8464-5b077c0ae689.png)
> Itong part baka merong library yung react para sa scrollable year/date picker? so depende na lang sa inyo. Once na integrate na yung scrollable year/date.(kung meron man) then if may papadagdag na design let me know na lang.

di ko lang sure pero pwede ata gamitin yung Date ng Js dyan

2021-12-05 02:33 UTC, glendell03 commented
> nice, @glendell03  okay lang palipat ulit to pri? yung nasa auditor.attendance ililipat sana ditoo 
> ![image](https://user-images.githubusercontent.com/71435340/144730789-8abb9e31-7926-4626-92d0-13068e48761c.png)
> 

sige sige

2022-02-18 12:29 UTC, yell66w requested changes
Pachange po ako nung component

2022-02-18 12:29 UTC, yell66w commented on frontend/src/containers/Attendance/index.jsx
>  export default Attendance;
Ano po ito? Bat nakalagay sa attendance?

2022-02-18 12:29 UTC, yell66w commented on frontend/src/containers/Attendance/index.jsx
>  export default Attendance;
conflict siguro to sa #201

2022-02-20 07:56 UTC, yell66w approved these changes

2022-02-20 07:56 UTC, merged